apiVersion : apps/v1
kind: Deployment
metadata:
  name: btcblazorkubernetes 
spec:
  selector:
    matchLabels:
      app: btcblazorkubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: btcblazorkubernetes 
    spec:
      containers:
        - name: btcblazorkubernetes 
          image: btcblazorserver.azurecr.io/btcblazorkubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
